// If we list all the natural numbers below 10 that are multiples of 3 or 5,
// we get 3, 5, 6 and 9. The sum of these multiples is 23.
//
// Find the sum of all the multiples of 3 or 5 below 1000.

function sumOfMult(x){
    let sum = 0;
    for(let i = 0; i < x; i++){
        if(i % 3 === 0){
            sum += i;
        } else if(i % 5 === 0){
            sum += i;
        } else {
            continue;
        }
    }
    return sum;
}

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms

function evenFibSum(max){
    let count = 0;
    let fibArray = [1, 2, 3];
    for(let i = 0; count < max; i++){
        let n = fibArray.length - 1;
        let next = (fibArray[n]) + (fibArray[n - 1]);
        fibArray.push(next);
        let evenFibArray = fibArray.filter((a) => a % 2 === 0);
        count = evenFibArray.reduce((a, b) => a + b);
    }
    return count;
}

//console.log(evenFibSum(4000000));

// The prime factors of 13195 are 5, 7, 13 and 29.
//
// What is the largest prime factor of the number 600851475143 ?
// % op up through 10 in a for loop against the parameter to check where to start
// not giving correct answer for large nums, the 13195 does return the 29
function largestPrimeFactor(x){
    let output = [x];
    let remain;
    let base = 2;
    for(let i = base; i < 100; i++){
        if(x % i === 0){
            remain = x / i;
            output.push(i);
            output.push(remain);
            break;
        }
    }
    for(let j = base; j < remain; j++){
        if(remain % j === 0){
            remain /= j;
            output.push(j);
            output.push(remain);
            break;
        }
    }
    for(let k = base; k < remain; k++){
        if(remain % k === 0){
            remain /= k;
            output.push(k);
            output.push(remain);
            break;
        }
    }
    for(let l = base; l < remain; l++){
        if(remain % l === 0){
            remain /= l;
            output.push(l);
            output.push(remain);
            break;
        }
    }
    for(let m = base; m < remain; m++){
        if(remain % m === 0){
            remain /= m;
            output.push(m);
            output.push(remain);
            break;
        }
    }
    //return output;
    return output[output.length - 1];
}

//console.log(largestPrimeFactor(76)); //correct, 19
//console.log(largestPrimeFactor(13195));// correct, 29
//console.log(largestPrimeFactor(999));// correct 37
//console.log(largestPrimeFactor(6008514751143));//output 1010131 which is prime

// A palindromic number reads the same both ways. The largest palindrome made from the product
// of two 2-digit numbers is 9009 = 91 × 99.
//
// Find the largest palindrome made from the product of two 3-digit numbers.

// the problem here is the inner loop decrements too much, need them to basically decrement together
function largestPalindromeProduct3Digits(){
    let currentHighest;
    let compare;
    for(let i = 999; i > 100; i--){
        for(let j = 999; j > 100; j--){
            currentHighest = i * j;
            compare = Number(currentHighest.toString().split("").reverse().join(""));
            if(currentHighest === compare){
                return currentHighest;
            }
        }
    }
}
//console.log(largestPalindromeProduct3Digits());

// 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
//
//     What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
//1,2,3,4,5,6,7,8,9,10,12,14,15,16,18,20
// 16 --- 2, 4, 8, 16
// 15 --- 3, 5, 15
// 12 --- 3, 4, 6, 12
// 18 --- 2, 9, 18
// 20 --- 2, 4, 5, 10, 20
// 14 --- 7, 14, 2
// 11
// 13
// 17
// 19
function smallestNumDivisible(){
    for(let i = 1; i < 300000000; i++){
        if(i % 16 === 0 && i % 15 === 0 && i % 12 === 0 && i % 18 === 0 && i % 20 === 0 && i % 14 === 0 && i % 11 === 0 && i % 13 === 0 && i % 17 === 0 && i % 19 === 0){
            return i;
        }
    }
}
//232,792,560
//console.log(smallestNumDivisible());

// array of both square then sum and sum then square, use map and reduce and find difference
function sumSquareDifference(n){

}